[theme]

# Primary accent for interactive elements
primaryColor = '#A6D388'

# Background color for the main content area
backgroundColor = '#F2F2F2'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#29AF6F'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"